[project]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "DNO-1"
platforms = ["win-64"]
version = "0.1.0"


[dependencies]
python = "3.12.*"
pip = ">=25.0.1,<26"


[feature.game]
pypi-dependencies = {pyxel = ">=2.3.16, <3"}
tasks = { game = "python game.py" }


[feature.ecg]
pypi-dependencies = {dearpygui = ">=2.0.0, <3", pywavelets = ">=1.8.0, <2", numpy = ">=2.2.4, <3", pyserial = ">=3.5, <4"}
tasks = {ecg = "python plot_ecg.py"}


[environments]
game = ["game"]
ecg = ["ecg"]


